language: scala

os: linux

dist: xenial

scala: 
  - 2.13.2

jdk:
  - openjdk8
  - openjdk11

services:
  - docker

git:
  depth: 500

stages:
- name: test
- name: release
  if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
  - stage: release
    jdk: openjdk8
    script: docker login -u $DOCKER_USER -p $DOCKER_PASS && sbt docker:publish
    name: docker
  - script: sbt ci-release
    name: jar

before_install:
  - git fetch --tags

install:
  - pip install --user codecov

script: sbt ++$TRAVIS_SCALA_VERSION validate

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete

cache:
  directories:
  - $HOME/.cache/coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt

after_success:
- codecov

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0c488817d5dc313a8cc7
    on_success: change
    on_failure: always
    on_start: never
